global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  - to: 'Administrator@thematrix.eiland-x.be'
    from: 'Administrator@thematrix.eiland-x.be'
    smarthost: 10.10.20.4:587
    auth_username: 'Administrator@thematrix.eiland-x.be'
    auth_identity: 'Administrator@thematrix.eiland-x.be'
    auth_password: 'changeme'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']